### ISSUE TITLE
技能和人物碰撞这块是怎么处理的?

### ISSUE THREAD

**Issue by yyman001** [dddzg/MapleStory-cocos2d#1]
如果不是看源码, 这个其实应该很难模拟吧= =, 请问你是如何处理这块技能碰撞判断滴

**Comment by dddzg** [comment]
https://github.com/dddzg/MapleStory-cocos2d/blob/9a775a1156fefadc893b36a453f2e4b5be91c84a/Classes/MainScene.cpp#L463
